//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _190126_bireysel_proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDonate
    {
        public int DonateID { get; set; }
        public string DonateName { get; set; }
        public string DonateOrganization { get; set; }
        public string DonateType { get; set; }
        public Nullable<int> MonthlyDonations { get; set; }
        public string Address { get; set; }
    }
}
