//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployees
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string IdentityNumber { get; set; }
        public Nullable<decimal> AnnualSalary { get; set; }
        public Nullable<int> ContractID { get; set; }
    
        public virtual tblContracts tblContracts { get; set; }
    }
}
